config/routes.rb
Rails.application.routes.draw do
    
    # Devise routes
    devise_for :users, :controllers => { registrations: 'registrations' }
    
    # Root route
    root 'welcome#index', as: "home_page"
    
    # User routes
    get     '/users'            => 'users#index', as:  'users'
    get     '/users/new'        => 'users#new', as: 'new_user'
    post    '/users'            => 'users#create'
    get     '/users/:id'        => 'users#show', as: 'user'
#    get     '/users/:id/edit'   => 'users#edit', as: 'edit_user'
    put     '/users/:id'        => 'users#update'
    patch   '/users/:id'        => 'users#update'
    delete  '/users/:id'        => 'users#destroy'
    
    # Job routes
    get     '/jobs'             => 'jobs#index', as:  'jobs'
    get     '/jobs/new'         => 'jobs#new', as: 'new_job'
    post    '/jobs'             => 'jobs#create'
    get     '/jobs/:id'         => 'jobs#show', as: 'job'
    get     '/jobs/:id/edit'    => 'jobs#edit', as: 'edit_job'
    put     '/jobs/:id'         => 'jobs#update'
    patch   '/jobs/:id'         => 'jobs#update'
    delete  '/jobs/:id'         => 'jobs#destroy'
    
    # Boat routes
    get     '/boats'            => 'boats#index', as:  'boats'
    get     '/boats/new'        => 'boats#new', as: 'new_boat'
    post    '/boats'            => 'boats#create'
    get     '/boats/:id'        => 'boats#show', as: 'boat'
    get     '/boats/:id/edit'   => 'boats#edit', as: 'edit_boat'
    put     '/boats/:id'        => 'boats#update'
    patch   '/boats/:id'        => 'boats#update'
    delete  '/boats/:id'        => 'boats#destroy'
    
    
    resources :jobs do
        member do
            get :workers     
        end
    end
    
    resources :boats do
        member do
            get :tasks     
        end
    end
    
    resources :assignments,     only: [:create, :destroy]
    
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/job.rb
class Job < ApplicationRecord
    has_many :boats, :through => :assignments
    has_many :assignments

    validates(:name, uniqueness: true, presence: true, length: {minimum: 3})
    validates :origin, :destination, presence: true
    validates :description, presence: true, length: {minimum: 50}
    validates :cost, numericality: { :greater_than => 1000, :less_than_or_equal_to => 999999999}
    validates :cc, numericality: { :greater_than => 0, :less_than_or_equal_to => 99999}

    geocoded_by :address
    after_validation :geocode, :if => :address_changed?

    geocoded_by :location
    after_validation :geocode, :if => :location_changed?

    geocoded_by :origin
    after_validation :geocode, :if => :origin_changed?

    geocoded_by :destination
    after_validation :geocode, :if => :destination_changed?

    def self.search(search)
        where("name LIKE ?", "%#{search}%")
    end

    def assign(boat)
       assignments.create(boat_id: boat.id)
    end

    def unassign(boat)
       assignments.find_by(boat_id: boat.id).destroy
    end

    def assigned(boat)
       assignments.include?(boat)
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

    before_action :authenticate_user!
    def index
        @message = "index"
        @jobs = Job.all

        if params[:search]
            @jobs = Job.search(params[:search]).order("created_at DESC")
        else
            @jobs = Job.all.order('created_at DESC')
        end
    end

    def new
        @message = "new"
    end

    def create
        @message = "create"
        @new_job = Job.new(job_params)

        if @new_job.save
            redirect_to url_for(:controller => :jobs, :action => :index)
        else
            render 'new'
        end
    end

    def show
        @message = "show"
        @job = Job.find(params[:id])
    end

    def edit
        @message = "edit"
        @job = Job.find(params[:id])
    end

    def update
        @message = "update"
        @job = Job.find(params[:id])

        if @job.update_attributes(job_params)
            redirect_to url_for(:controller => :jobs, :action => :index)
        else
            render 'edit'
        end
    end

    def destroy
        @message = "destory"
        Job.delete(params[:id])
        redirect_to url_for(:controller => :jobs, :action => :index)
    end

    def workers
        @title = "Worker"
        @job  = Job.find(params[:id])
        @boats = @job.boats.paginate(page: params[:page])
        render 'show_follow'
    end

    private

    def job_params
       params.require(:job).permit(:name, :description, :origin, :destination, :latitude, :longitude, :address, :location, :cost, :cc) 
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/edit.html.erb
<h2>Job Edit</h2>
    <hr>
        <%= form_for @job, html: { multipart: true } do |f| %>
        <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control", placeholder: "Job Name" %>
            <small id="nameHelp" class="form-text text-muted">Title of the job.</small>
        </div>

        <div class='form-group row'>
            <div class="col-sm-6">
            <%= f.label :origin %>
            <%= f.text_field :origin, class: "form-control", placeholder: "Origin" %>
            </div>
            <div class="col-sm-6">
            <%= f.label :destination %>
            <%= f.text_field :destination, class: "form-control", placeholder: "Destination" %>
            </div>
        </div>

        <div class='form-group row'>
            <div class="col-sm-6">
            <%= f.label :Cost %>
            <%= f.number_field :cost, class: "form-control", placeholder: "Cost" %>
            </div>
            <div class="col-sm-6">
            <%= f.label :Container_Count %>
            <%= f.number_field :cc, class: "form-control", placeholder: "Container Count" %>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-12">
                <%= f.label :Details %>
                <%= f.text_area :description, class: "form-control", placeholder: "Extra job details here", rows: "3" %>
            </div>
        </div>

        <div class="form-group">
            <%= f.submit "Update Boat", class: "btn btn-primary" %>    
        </div>
<% end %>

app/views/jobs/index.html.erb
<h2>Jobs</h2>

<% @jobs.each do |job| %>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4>
                <small><%= job.id %>.</small>
                <%= job.name %>
            </h4>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-sm-2" style="overflow:hidden">
                    <!-- COMPANY LOGO-->
                    <%= image_tag current_user.logo.url, class: "img-rounded img-responsive" %>
                </div>
                <div class="col-sm-10">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Cost</th>
                                <th>Orign</th>
                                <th>Destination</th>
                                <th>Containers</th>
                                <th>Latitude</th>
                                <th>Longitude</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>$<%= job.cost %></td>
                                <td><%= job.origin %></td>
                                <td><%= job.destination %></td>
                                <td><%= job.cc %></td>
                                <td><%= job.latitude %></td>
                                <td><%= job.longitude %></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="panel-footer clearfix">
            <div class="pull-right">
                <%= link_to 'Read more', job_path(job.id), class: "btn btn-primary btn-sm" %>
            </div>
        </div>
    </div>
<% end  %>


<div class="row">
    <div class="col-sm-12">
        <%= button_to 'new', new_job_path, class: "btn btn-primary", :method => "get" %>
    </div>
</div>

app/views/jobs/new.html.erb
<h2>New Job</h2>

<%= form_for Job.new do |f| %>

    <div class='form-group row'>
        <div class="col-sm-12">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
        </div>
    </div>

    <div class='form-group row'>
        <div class="col-sm-6">
        <%= f.label :origin %>
        <%= f.text_field :origin, class: "form-control", placeholder: "Origin" %>
        </div>
        <div class="col-sm-6">
        <%= f.label :destination %>
        <%= f.text_field :destination, class: "form-control", placeholder: "Destination" %>
        </div>
    </div>

    <div class='form-group row'>
        <div class="col-sm-6">
            <%= f.label :Cost %>
            <div class = "input-group">
                <span class = "input-group-addon">$</span>
                <%= f.number_field :cost, class: "form-control", placeholder: "Cost" %>
                <span class = "input-group-addon">.00</span>
            </div>
        </div>
        <div class="col-sm-6">
        <%= f.label :Container_Count %>
        <%= f.number_field :cc, class: "form-control", placeholder: "Container Count" %>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-sm-12">
            <%= f.label :Details %>
            <%= f.text_area :description, class: "form-control", placeholder: "Extra job details here", rows: "3" %>
        </div>
    </div>

    <div class="form-group row">
       <div class="col-sm-12">
           <%= f.submit "Create new job", class: "btn btn-lg btn-primary btn-block" %>
        </div>
    </div>
<% end %>

app/views/jobs/show.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-sm-12">
                <h4><%= @job.name %></h4>
            </div>
        </div>
    </div>

    <div class="panel-body">

        <div class="row">
            <div class="col-sm-12">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Cost</th>
                            <th>Orign</th>
                            <th>Destination</th>
                            <th>Containers</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>$<%= @job.cost %></td>
                            <td><%= @job.origin %></td>
                            <td><%= @job.destination %></td>
                            <td><%= @job.cc %></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <h3>Job Details</h3>
        <hr>
        <!--VALUES-->
        <div class="row">
            <div class="col-sm-12">
                    <%= @job.description %>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12">
              
              <div id="mapst">
                <%= image_tag "http://maps.googleapis.com/maps/api/staticmap?size=450x300&sensor=false&zoom30&markers=#{@job.latitude},#{@job.longitude}&markers=#{@job.latitude},#{@job.longitude}&zoom=7&size=640x400&key=AIzaSyA4BHW3txEdqfxzdTlPwaHsYRSZbfeIcd8",
                            class: 'img-fluid img-rounded', alt: "#{@job.address} on the map"%>
              </div>

                <div class="btn-toolbar ">
                      <div class="btn-group pull-right">
                    <%= button_to 'Delete', { action: :destroy, id: @job.id }, class: "btn btn-danger btn-xs", method: :delete %>

                    </div>
                      <div class="btn-group pull-right">
                    <%= button_to 'Edit', edit_job_path, class: "btn btn-success btn-xs", method: "get" %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<hr>
<div class="panel panel-default">
    <div class="panel-heading">
    Assigned Boats
    </div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Container Count</th>
                <th>Remove</th>
            </tr>
        </thead>
        <tbody>
            <% @job.assignments.all.each do |ass| %>
            <tr>
                <td><%= ass.boat_id %></td>
                <td><%= link_to Boat.all.find(ass.boat_id).name, boat_path(ass.boat_id) %></td>
                <td><%= Boat.all.find(ass.boat_id).ccc %></td>
                <td>
    <!--                ONLY A USER WHO CONTROLS THIS BOAT CAN REMOVE THE BOAT-->
                    <% if Boat.all.find(ass.boat_id).user_id == current_user.id %>
                        <%= form_for(@job.assignments.find_by(boat_id: ass.boat_id), html: { method: :delete }) do |f| %>
                        <%= hidden_field_tag :job_id, @job.id %>

                        <%= button_tag class: "btn btn-danger btn-xs" do %>
                            <i class="glyphicon glyphicon-remove"></i>
                        <% end %>

                        <% end %>
                    <% elsif %>
                        <button class="btn btn-danger btn-xs" disabled="disabled">
                                <i class="glyphicon glyphicon-remove"></i>
                            </button>
                    <% end %>
                </td>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>

<%= form_for @job.assignments.build, html: {class: "form-inline"} do |f| %>
    <div class="form-group">
        <label for="exampleSelect1">Assign boat to job</label>
        <%= f.collection_select :boat_id, current_user.boats.each, :id, :name, { include_blank: true}, {:class => "form-control"} %>

        <%= hidden_field_tag :job_id, @job.id %>
        <%= f.submit "Add", class: "btn btn-primary" %>
    </div>
<% end %>