config/routes.rb
Rails.application.routes.draw do
    
    # Devise routes
    devise_for :users, :controllers => { registrations: 'registrations' }
    
    # Root route
    root 'welcome#index', as: "home_page"
    
    # User routes
    get     '/users'            => 'users#index', as:  'users'
    get     '/users/new'        => 'users#new', as: 'new_user'
    post    '/users'            => 'users#create'
    get     '/users/:id'        => 'users#show', as: 'user'
#    get     '/users/:id/edit'   => 'users#edit', as: 'edit_user'
    put     '/users/:id'        => 'users#update'
    patch   '/users/:id'        => 'users#update'
    delete  '/users/:id'        => 'users#destroy'
    
    # Job routes
    get     '/jobs'             => 'jobs#index', as:  'jobs'
    get     '/jobs/new'         => 'jobs#new', as: 'new_job'
    post    '/jobs'             => 'jobs#create'
    get     '/jobs/:id'         => 'jobs#show', as: 'job'
    get     '/jobs/:id/edit'    => 'jobs#edit', as: 'edit_job'
    put     '/jobs/:id'         => 'jobs#update'
    patch   '/jobs/:id'         => 'jobs#update'
    delete  '/jobs/:id'         => 'jobs#destroy'
    
    # Boat routes
    get     '/boats'            => 'boats#index', as:  'boats'
    get     '/boats/new'        => 'boats#new', as: 'new_boat'
    post    '/boats'            => 'boats#create'
    get     '/boats/:id'        => 'boats#show', as: 'boat'
    get     '/boats/:id/edit'   => 'boats#edit', as: 'edit_boat'
    put     '/boats/:id'        => 'boats#update'
    patch   '/boats/:id'        => 'boats#update'
    delete  '/boats/:id'        => 'boats#destroy'
    
    
    resources :jobs do
        member do
            get :workers     
        end
    end
    
    resources :boats do
        member do
            get :tasks     
        end
    end
    
    resources :assignments,     only: [:create, :destroy]
    
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/boat.rb
class Boat < ApplicationRecord
    belongs_to :user
    has_many :jobs, :through => :assignments
    has_many :assignments

    validates :name, uniqueness: true, presence: true
    validates :location, presence: true
    validates :ccc, numericality: { :greater_than => 0, :less_than_or_equal_to => 9999}

    geocoded_by :address
    after_validation :geocode, :if => :address_changed?

    geocoded_by :location
    after_validation :geocode, :if => :location_changed?

    def self.search(search)
        where("name LIKE ?", "%#{search}%")
    end
end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController

    before_action :authenticate_user!
    def index
        @message = "index"
        @boats = Boat.all

        if params[:search]
            @boats = Boat.search(params[:search]).order("created_at DESC")
        else
            @boats = Boat.all.order('created_at DESC')
        end
    end

    def new
        @message = "new"
    end

    def create
        @message = "create"
        @new_boat = Boat.new(boat_params)

        if @new_boat.save
            redirect_to url_for(:controller => :boats, :action => :index)
        else
            render 'new'
        end
    end

    def show
        @message = "show"
        @boat = Boat.find(params[:id])
    end

    def edit
        @message = "edit"
        @boat = Boat.find(params[:id])
    end

    def update
        @message = "update"
        @boat = Boat.find(params[:id])

        if @boat.update_attributes(boat_params)
            redirect_to url_for(:controller => :boats, :action => :index)
        else
            render 'edit'
        end
    end

    def destroy
        @message = "destory"
        Boat.delete(params[:id])
        redirect_to boats_path
        # redirect_back(fallback_location: :back)
    end

    private

    def boat_params
       params.require(:boat).permit(:name, :location, :origin, :address, :destination, :latitude, :longitude, :ccc, :user_id)
    end
end

app/helpers/boats_helper.rb
module BoatsHelper
end

app/views/boats/edit.html.erb
<h2>Boat Edit</h2>
    <hr>
        <%= form_for @boat, html: { multipart: true } do |f| %>
        <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control", placeholder: "Boat Name" %>
            <small id="nameHelp" class="form-text text-muted">Name of the boat.</small>
        </div>

        <div class="form-group">
            <%= f.label :location %>
            <%= f.text_field :address, class: "form-control", placeholder: "Location" %>
            <small id="nameHelp" class="form-text text-muted">Where the boat is currently docked.</small>
        </div>

        <div class='form-group row'>
            <div class="col-sm-12">
            <%= f.label :Container_Carry_Count %>
            <%= f.number_field :ccc, class: "form-control", placeholder: "Count" %>
            </div>
        </div>

        <div class="form-group">
            <%= f.submit "Update Boat", class: "btn btn-primary" %>
        </div>
<% end %>

app/views/boats/index.html.erb
<h2>Boats</h2>

<% @boats.each do |boat| %>
    <div class="panel panel-default">
        
        <div class="panel-heading">
            <h4>
                <small><%= boat.id %>.</small>
                <%= boat.name %>
            </h4>
        </div>
        
        <div class="panel-body">
            <!--VALUES-->
            LOCATION: <%= boat.location %>
            CCC: <%= boat.ccc %>
            <br>
        </div>
        
        <div class="panel-footer clearfix">
            <div class="pull-right">
                <%= link_to 'Read more', boat_path(boat.id), class: "btn btn-primary btn-sm" %>
            </div>
        </div>
    </div>
<% end  %>

<div class="row">
    <div class="col-sm-12">
        <%= button_to 'new', new_boat_path, class: "btn btn-primary", :method => "get" %>
    </div>
</div>

app/views/boats/new.html.erb
<%= form_for Boat.new do |f| %>
    <h2>New Boat</h2>

    <div class='form-group row'>
        <div class="col-sm-12">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
        </div>
    </div>

    <div class='form-group row'>
        <div class="col-sm-12">
        <%= f.label :location %>
        <%= f.text_field :location, class: "form-control", placeholder: "Location" %>
        </div>
    </div>

    <div class='form-group row'>
        <div class="col-sm-12">
        <%= f.label :Container_Carry_Count %>
        <%= f.number_field :ccc, class: "form-control", placeholder: "Count" %>
        </div>
    </div>

    <%= f.hidden_field :user_id, :value => current_user.id %>

    <div class="form-group row">
       <div class="col-sm-12">
           <%= f.submit "Create new boat", class: "btn btn-lg btn-primary btn-block" %>
        </div>
    </div>
<% end %>

app/views/boats/show.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-sm-12">
                <h4><i class="fa fa-ship"></i>
                &emsp;
                <%= @boat.name %></h4>
            </div>
        </div>
    </div>

    <div class="panel-body">

        <div class="row">
            <div class="col-sm-12">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Location</th>
                            <th>Container</th>
                            <th>Owner</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><%= @boat.location %></td>
                            <td><%= @boat.ccc %></td>
                            <td><%= User.all.find(@boat.user.id).fname %></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <% if user_signed_in? && @boat.user.id == current_user.id %>
    <div class="panel-footer">
        <div class="row">
            <div class="col-sm-12">

              <%= image_tag "http://maps.googleapis.com/maps/api/staticmap?size=450x300&sensor=false&zoom30&markers=#{@boat.latitude},#{@boat.longitude}&markers=#{@boat.latitude},#{@boat.longitude}&zoom=7&size=640x400&key=AIzaSyA4BHW3txEdqfxzdTlPwaHsYRSZbfeIcd8",
                          class: 'img-fluid img-rounded', alt: "#{@boat.address} on the map"%>

                <div class="btn-toolbar ">
                      <div class="btn-group pull-right">
                    <%= button_to 'Delete', { action: :destroy, id: @boat.id }, class: "btn btn-danger btn-xs", method: :delete %>
                    </div>
                      <div class="btn-group pull-right">
                    <%= button_to 'Edit', edit_boat_path, class: "btn btn-success btn-xs", method: "get" %>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <% end %>
</div>

<div class="panel panel-default">

        <div class="panel-heading">
            Assigned Jobs
        </div>

        <table class="table table-striped">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Remove</th>
                </tr>
            </thead>
            <tbody>
                <% @boat.assignments.all.each do |ass| %>
                    <tr>
                        <td><%= ass.job_id %></td>
                        <td><%= link_to Job.find(ass.job_id).name, job_path(ass.job_id) %></td>
                        <td>

        <!--                ONLY A USER WHO CONTROLS THIS BOAT CAN REMOVE THE BOAT-->
                        <% if user_signed_in? && @boat.user.id == current_user.id %>
                            <%= form_for(Job.find(ass.job_id).assignments.find_by(boat_id: ass.boat_id), html: { method: :delete }) do |f| %>
                                <%= hidden_field_tag :job_id, ass.job_id %>

                                <%= button_tag class: "btn btn-danger btn-xs" do %>
                                    <i class="glyphicon glyphicon-remove"></i>
                                <% end %>
                            <% end %>

                        <% elsif %>
                            <button class="btn btn-danger btn-xs" disabled="disabled">
                                <i class="glyphicon glyphicon-remove"></i>
                            </button>
                        <% end %>
                    </td>

                    </tr>
                <% end %>
            </tbody>
        </table>


</div>