config/routes.rb
Rails.application.routes.draw do
    
    # Devise routes
    devise_for :users, :controllers => { registrations: 'registrations' }
    
    # Root route
    root 'welcome#index', as: "home_page"
    
    # User routes
    get     '/users'            => 'users#index', as:  'users'
    get     '/users/new'        => 'users#new', as: 'new_user'
    post    '/users'            => 'users#create'
    get     '/users/:id'        => 'users#show', as: 'user'
#    get     '/users/:id/edit'   => 'users#edit', as: 'edit_user'
    put     '/users/:id'        => 'users#update'
    patch   '/users/:id'        => 'users#update'
    delete  '/users/:id'        => 'users#destroy'
    
    # Job routes
    get     '/jobs'             => 'jobs#index', as:  'jobs'
    get     '/jobs/new'         => 'jobs#new', as: 'new_job'
    post    '/jobs'             => 'jobs#create'
    get     '/jobs/:id'         => 'jobs#show', as: 'job'
    get     '/jobs/:id/edit'    => 'jobs#edit', as: 'edit_job'
    put     '/jobs/:id'         => 'jobs#update'
    patch   '/jobs/:id'         => 'jobs#update'
    delete  '/jobs/:id'         => 'jobs#destroy'
    
    # Boat routes
    get     '/boats'            => 'boats#index', as:  'boats'
    get     '/boats/new'        => 'boats#new', as: 'new_boat'
    post    '/boats'            => 'boats#create'
    get     '/boats/:id'        => 'boats#show', as: 'boat'
    get     '/boats/:id/edit'   => 'boats#edit', as: 'edit_boat'
    put     '/boats/:id'        => 'boats#update'
    patch   '/boats/:id'        => 'boats#update'
    delete  '/boats/:id'        => 'boats#destroy'
    
    
    resources :jobs do
        member do
            get :workers     
        end
    end
    
    resources :boats do
        member do
            get :tasks     
        end
    end
    
    resources :assignments,     only: [:create, :destroy]
    
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>OceanicRails</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    </head>

    <body>            
        <div class="container">
            
            <br>
            <nav role="navigation" class="navbar navbar-default">
                <div class="navbar-header">
                    <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="/" class="navbar-brand "><span class="glyphicon glyphicon-queen"></span></a>
                </div>
                
                <div id="navbarCollapse" class="collapse navbar-collapse">
                    <% if user_signed_in? %>
                    <ul class="nav navbar-nav">
<!--                        <li class="active"><a href="#">Home</a></li>-->
                        <li><%= link_to "Profile", user_path(current_user) %></li>
                        
                        <li><%= link_to "User", users_path %></li>
                        <li><%= link_to "Jobs", jobs_path %></li>
                        
                        <li class="dropdown">
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">Boats<b class="caret"></b></a>
                            <ul role="menu" class="dropdown-menu">
                            <li><%= link_to "List", boats_path %></li>
                            <li><%= link_to "Add", new_boat_path %></li>
                            <li class="divider"></li>
                            </ul>
                        </li>
                    </ul>
                    
                    <%= form_for(request.original_url, :method => "get", id: "search-form", :html => {:class => "navbar-form navbar-left"}) do %>
                        <div class="form-group">
                        <%= text_field_tag :search, params[:search], class: 'form-control', placeholder: "Search "+request.path %>
                        </div>
                    <% end %>
                    
                    <% end %>
                    
                    <ul class="nav navbar-nav navbar-right">
                        <% if user_signed_in? %>
                            <li><%= link_to 'Sign Out',  { :action=>"destroy", :controller=>"devise/sessions" }, method: :delete %></li>
                        <% else %>
                            <li><%= link_to "Login", new_user_session_path %></li>
                            <li><%= link_to "Register", new_user_registration_path %></li>
                        <% end %>
                    </ul>
                </div>
            </nav>
                  
            <%= yield %>
        
            <footer class="footer">
                    <p class="text-muted" style="float:right; color:black">&copy; 2016 - Made by a Guppy</p>
            </footer>
        </div>

        <div class="container-fluid">
            <p class="notice"><%= notice %></p>
            <p class="alert"><%= alert %></p>
        </div>
    </body>
</html>